name: movies_asd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  dartz: ^0.10.1
  get_it: ^8.0.3
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.1
  hive_test: ^1.0.1
  path_provider_platform_interface: ^2.0.4

flutter:
  uses-material-design: true

